# Generated by Django 5.0.3 on 2024-03-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_alter_fotografia_publicada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank='', upload_to='fotos'),
        ),
    ]
